name: Cypress E2E tests

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload .next directory
        uses: actions/upload-artifact@v4
        with:
          name: next-app
          path: ./.next

  run-e2e-tests:
    needs: build-app
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download .next directory
        uses: actions/download-artifact@v4
        with:
          name: next-app
          path: ./.next

      - name: Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          command-prefix: 'npx cypress run'
